language: node_js

node_js: 
  - "node"
  - "10"
  - "9"
  - "8"

before_install:
  - "npm install babel-cli react-native-cli -g"

before_script:
  - "npm install react react-native"
  - "npm install"

cache:
  directories:
    - "node_modules"

script:
	- "npm run test"
